# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import booking_pb2 as booking__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getBookingByUserId = channel.unary_unary(
                '/Booking/getBookingByUserId',
                request_serializer=booking__pb2.BookingUser.SerializeToString,
                response_deserializer=booking__pb2.BookingUser.FromString,
                _registered_method=True)
        self.addBookingByUserId = channel.unary_unary(
                '/Booking/addBookingByUserId',
                request_serializer=booking__pb2.AddBooking.SerializeToString,
                response_deserializer=booking__pb2.BookingUser.FromString,
                _registered_method=True)
        self.deleteBooking = channel.unary_unary(
                '/Booking/deleteBooking',
                request_serializer=booking__pb2.DeleteBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.DeleteBookingResponse.FromString,
                _registered_method=True)


class BookingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getBookingByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addBookingByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getBookingByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.getBookingByUserId,
                    request_deserializer=booking__pb2.BookingUser.FromString,
                    response_serializer=booking__pb2.BookingUser.SerializeToString,
            ),
            'addBookingByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.addBookingByUserId,
                    request_deserializer=booking__pb2.AddBooking.FromString,
                    response_serializer=booking__pb2.BookingUser.SerializeToString,
            ),
            'deleteBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteBooking,
                    request_deserializer=booking__pb2.DeleteBookingRequest.FromString,
                    response_serializer=booking__pb2.DeleteBookingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Booking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Booking', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Booking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getBookingByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Booking/getBookingByUserId',
            booking__pb2.BookingUser.SerializeToString,
            booking__pb2.BookingUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def addBookingByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Booking/addBookingByUserId',
            booking__pb2.AddBooking.SerializeToString,
            booking__pb2.BookingUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Booking/deleteBooking',
            booking__pb2.DeleteBookingRequest.SerializeToString,
            booking__pb2.DeleteBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
